[package]
name = "transformer"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.9.1"
candle-metal = "0.27.1"
candle-nn = "0.9.1"
ndarray = "0.16.1"
ndarray-rand = "0.15.0"
rand = "0.9.1"
anyhow = "1.0"
